name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: shell test
      run: |
# export ORIGIN_MONGO_URI_DEV=${{ secrets.ORIGIN_MONGO_URI_DEV }}
        bash ${GITHUB_WORKSPACE}/example.sh test
